language: python
python:
  - "2.7"
  
cache:
  pip: true
  directories:
  - $HOME/.ccache
  
env:
  - SIMPHONY_VERSION=master
  - SIMPHONY_VERSION=0.5.0
matrix:
  allow_failures:
    - env: SIMPHONY_VERSION=master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mpi-default-bin mpi-default-dev ccache
  - sudo ln -s ccache /usr/local/bin/mpic++
  - export PATH=/usr/lib/ccache:${PATH}
  - ccache -s

install:
  # build and install liggghts
  - ./install_external.sh
  # Set paths manually for the case of installation procedure failed
  - export PATH=$PATH:$PWD/myliggghts/src/
  - export PYTHON_PATH=$PYTHON_PATH:$PWD/myliggghts/python/
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/myliggghts/src/
  - pip install -r dev_requirements.txt
  - pip install git+https://github.com/simphony/simphony-common.git@${SIMPHONY_VERSION}#egg=simphony
  - pip install -r doc_requirements.txt
  - python setup.py develop

script:
  - flake8 --exclude=myliggghts .
  - coverage run -m unittest discover
  - python setup.py build_sphinx

after_success:
  - pip install codecov
  - codecov
